# CMake generated Testfile for 
# Source directory: /home/liuyunqi/ymyu/libhwmath
# Build directory: /home/liuyunqi/ymyu/libhwmath/build_c
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[C_MODEL_TEST_RND_NEAREST_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_ONE" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEAREST_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEAREST_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEAREST_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEAREST_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_ZERO_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEAREST_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEAREST_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_1_NAN" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEAREST_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEAREST_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_REG" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEAREST_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_ZERO_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_ONE" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_ZERO_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_ZERO_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_ZERO_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_ZERO_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_ZERO_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_ZERO_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_ZERO_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_1_NAN" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_ZERO_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_ZERO_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_REG" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_ZERO_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_POS_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_ONE" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_POS_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_POS_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_POS_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_POS_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_ZERO_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_POS_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_POS_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_1_NAN" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_POS_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_POS_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_REG" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_POS_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEG_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_ONE" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEG_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEG_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEG_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEG_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_ZERO_INF" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEG_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEG_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_1_NAN" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEG_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[C_MODEL_TEST_RND_NEG_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_REG" "TEST_MONTE")
set_tests_properties([=[C_MODEL_TEST_RND_NEG_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;42;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEAREST_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_ONE" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEAREST_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEAREST_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEAREST_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEAREST_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_ZERO_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEAREST_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEAREST_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_1_NAN" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEAREST_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEAREST_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEAREST" "TEST_REG" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEAREST_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_ZERO_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_ONE" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_ZERO_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_ZERO_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_ZERO_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_ZERO_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_ZERO_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_ZERO_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_ZERO_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_1_NAN" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_ZERO_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_ZERO_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_ZERO" "TEST_REG" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_ZERO_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_POS_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_ONE" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_POS_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_POS_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_POS_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_POS_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_ZERO_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_POS_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_POS_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_1_NAN" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_POS_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_POS_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_POS" "TEST_REG" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_POS_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEG_TEST_ONE]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_ONE" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEG_TEST_ONE]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEG_TEST_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEG_TEST_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEG_TEST_ZERO_INF]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_ZERO_INF" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEG_TEST_ZERO_INF]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEG_TEST_1_NAN]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_1_NAN" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEG_TEST_1_NAN]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
add_test([=[RTL_MODEL_TEST_RND_NEG_TEST_REG]=] "/home/liuyunqi/ymyu/libhwmath/build_c/mul" "TEST_RND_NEG" "TEST_REG" "TEST_RTL" "TEST_MONTE")
set_tests_properties([=[RTL_MODEL_TEST_RND_NEG_TEST_REG]=] PROPERTIES  _BACKTRACE_TRIPLES "/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;49;add_test;/home/liuyunqi/ymyu/libhwmath/CMakeLists.txt;0;")
